/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sinieco_ffmpeg_demo_PlayController */

#ifndef _Included_com_sinieco_ffmpeg_demo_PlayController
#define _Included_com_sinieco_ffmpeg_demo_PlayController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sinieco_ffmpeg_demo_PlayController
 * Method:    render
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_sinieco_ffmpeg_1demo_PlayController_render
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_sinieco_ffmpeg_demo_PlayController
 * Method:    sound
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sinieco_ffmpeg_1demo_PlayController_sound
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
